### ISSUE TITLE
Add `JsonProperty` attributes to data models.

### ISSUE THREAD

**Issue by tacosontitan** [globallcs/Spottr.Net#11]
Our data models currently do not adhere to the naming conventions of JSON, and this is correct, in our code. However, since the models will be transmitted via JSON into a JavaScript environment, we should map the names to the conventions of JSON (e.g. `myProperty` vs. `MyProperty`).

**Comment by tacosontitan** [comment]
Please use the `Newtonsoft.Json` attribute for this and ensure the attribute is inline with the properties, for example:

```cs
[JsonProperty("myProperty", NullValueHandling = NullValueHandling.Ignore)] public string MyProperty { get; set; }
```

**Comment by tacosontitan** [comment]
Additionally, this only applies to the `Spottr.Net` project for the time being. If we need this in additional projects, we'll tackle those on a case-by-case basis.

**Comment by SuthrnDLT** [comment]
Please assign this to me.
