### ISSUE TITLE
Fix namespace for `DisplayState`.

### ISSUE THREAD

**Issue by tacosontitan** [globallcs/Spottr.Net#14]
Currently the `DisplayState` enum is designating `Spottr.Net.Packets` as its containing namespace:

![image](https://user-images.githubusercontent.com/65432314/174408839-b68b9b0b-7c7d-400f-8916-e3654c56b955.png)

Remove the `.Packets` namespace as this enum is defined at the root level of `Spottr.Net`.

**Comment by aseemsahoo** [comment]
Please assign this task to me. Thanks.

**Comment by aseemsahoo** [comment]
Have given a PR request for 2 ongoing issues.
